[package]
name = "mg-pkg-obs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mg_pkg_obs"
crate-type = ["dylib"]

[dependencies]
macrograph-core-types = { path = "../../core/types" }
obws = { git = "https://github.com/dnaka91/obws.git", branch = "v5-api", features = ["events"] }
futures = "0.3.19"
tokio = {version = "1.16.1", features = ["rt", "rt-multi-thread"]}
