[package]
name = "macrograph-pkg-keyboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdev = { git = "https://github.com/Brendonovich/rdev", features = ["macos_noloop"] }
macrograph = { path = "../../core" }
serde_json = "1.0.68"
serde = "1.0.130"
