[package]
name = "macrograph-packages"
version = "0.0.0"

[lib]
name = "macrograph_packages"
path = "lib.rs"

[dependencies]
macrograph-core = { path = "../core" }
mg-pkg-logic = { path = "./logic" }
mg-pkg-keyboard = { path = "./keyboard" }
mg-pkg-midi = { path = "./midi" }
mg-pkg-utils = { path = "./utils" }
mg-pkg-obs = { path = "./obs" }