[package]
name = "macrograph-packages"
version = "0.0.0"
edition = "2021"

[lib]
name = "macrograph_packages"
path = "lib.rs"

[dependencies]
macrograph = { path = "../core" }

macrograph-pkg-keyboard = { path = "./keyboard"}
macrograph-pkg-midi = { path = "./midi"}
macrograph-pkg-utils = { path = "./utils"}